In [17]:
import numpy as np
import pandas as pd

In [18]:
df1 = pd.read_csv("ci/YasMarina_2016_gap_1.csv")
df2 = pd.read_csv("ci/YasMarina_2016_gap_2.csv")
df3 = pd.read_csv("ci/YasMarina_2016_gap_3.csv")
df4 = pd.read_csv("ci/YasMarina_2016_gap_4.csv")
df5 = pd.read_csv("ci/YasMarina_2016_gap_5.csv")
df6 = pd.read_csv("ci/YasMarina_2016_gap_6.csv")
df7 = pd.read_csv("ci/YasMarina_2016_gap_7.csv")
df8 = pd.read_csv("ci/YasMarina_2016_gap_8.csv")
df9 = pd.read_csv("ci/YasMarina_2016_gap_9.csv")
df10 = pd.read_csv("ci/YasMarina_2016_gap_10.csv")

dfs = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10]

In [24]:
dists = []
for df in dfs:
    dist = np.array(df[df.iloc[:, 0] == "VET"].iloc[0,1:])
    print(type(dist))
    dists.append(dist)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [26]:
dists

[array([20, 61, 88, 119, 400, 298, 9, 3, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0], dtype=object),
 array([23, 60, 63, 139, 390, 323, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0], dtype=object),
 array([24, 66, 62, 146, 385, 312, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0], dtype=object),
 array([14, 55, 67, 133, 414, 314, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0], dtype=object),
 array([16, 48, 75, 144, 402, 305, 8, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0], dtype=object),
 array([20, 73, 65, 130, 397, 312, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0], dtype=object),
 array([21, 55, 81, 131, 379, 330, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0], dtype=object),
 array([22, 52, 80, 140, 386, 315, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0], dtype=object),
 array([22, 52, 79, 137, 405, 302, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0], dtype=object),
 array([13, 69, 74, 131, 382, 326, 4,

In [30]:
df_stats = pd.DataFrame(dists)
mean = np.mean(df_stats, axis = 0)
st = np.std(df_stats, axis = 0)

counter = 1
for m, s in zip(mean, st):
    print(f"Place {counter}: {m} +/- {s}")
    counter += 1

Place 1: 19.5 +/- 3.640054944640259
Place 2: 59.1 +/- 7.7517739905133975
Place 3: 73.4 +/- 8.357032966310472
Place 4: 135.0 +/- 7.509993342207435
Place 5: 394.0 +/- 10.770329614269007
Place 6: 313.7 +/- 9.849365461794987
Place 7: 3.9 +/- 2.4269322199023198
Place 8: 0.8 +/- 0.9797958971132713
Place 9: 0.2 +/- 0.4
Place 10: 0.1 +/- 0.30000000000000004
Place 11: 0.1 +/- 0.30000000000000004
Place 12: 0.1 +/- 0.30000000000000004
Place 13: 0.0 +/- 0.0
Place 14: 0.0 +/- 0.0
Place 15: 0.0 +/- 0.0
Place 16: 0.0 +/- 0.0
Place 17: 0.1 +/- 0.30000000000000004
Place 18: 0.0 +/- 0.0
Place 19: 0.0 +/- 0.0
Place 20: 0.0 +/- 0.0
Place 21: 0.0 +/- 0.0
Place 22: 0.0 +/- 0.0


In [21]:
print(mean)
print(st)

[19.5 59.1 73.4 135.0 394.0 313.7 3.9 0.8 0.2 0.1 0.1 0.1 0.0 0.0 0.0 0.0
 0.1 0.0 0.0 0.0 0.0 0.0]


NameError: name 'st' is not defined